version: "3"
services:
    node-latest:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-latest
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
        command: "npm start"

    node-9:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-9
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
        command: "npm start"

    node-8:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-8
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
        command: "npm start"
